### ISSUE TITLE
New release to PyPI?

### ISSUE THREAD

**Issue by jvnn** [karel1980/OpenWebNet#2]
Hi! I'm using your library (thank you for all the work!) to connect my bus to home-assistant using the GatewayProxy and some glue code of my own, and although reading light states works fine, it seems that sending commands stops working soon after I've started the proxy. Do you know if the latest changes you've made could improve on this, and are you planning to make a new release to PyPI?

I wanted to track down and hopefully fix the problem myself, but I haven't had any time for private development work since months. If that ever gets better, I'm planning to add the whole addon and supporting tools library (e.g. simple device-address-to-name mapping tooling) that I wrote to GitHub for others to use as well.

**Comment by karel1980** [comment]
Hi. Sorry for the late response. I'm not really monitoring github replies :-/ I'm certainly interested in improving things.
The gateway proxy should just work. If it doesn't for you, that's a bug. I'm not at home right now, but I'll run a few experiments when I get back (today or tomorrow).
Is your glue code available for inspection somewhere?

**Comment by karel1980** [comment]
My current plan of attack is to make an easy to use, rock solid MQTT bridge - that way every mqtt-compatible system should be able to integrate with Openwebnet. This also has 2 options for stable connections:
- Detect connection loss / reconnect automatically
- If I can't get that to work reliably, it should be stable for at least a day & restarting it daily during the night should make things stable enough.

**Comment by jvnn** [comment]
Hi, and no worries about late responses, I'm not doing any better here. :) My glue code is unfortunately not yet available anywhere, and I haven't had any time for this project since a couple of months. I'll try to get back to it later this year, and will let you know if I find something.

**Comment by karel1980** [comment]
I've found the time to iron out a few mistakes and to simplify the code; I'm still figuring out the python asyncio stuff as I go so it's not 100% guaranteed.

2.0.0-rc1 is now released: https://pypi.org/project/reopenwebnet/2.0.0rc1/

The mqtt bridge should be good to go, but it won't recover after connection loss from the event client; This could be mitigated by restarting the script every now and then.

I would greatly appreciate feedback, so please let me know what you think.
